<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class AsesiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $asesiData = [
            // Kelompok 1
            [
                'name' => 'Muhamad Fadly Febrian',
                'nik' => '3275011811020001',
                'nim' => '2110512001',
                'telephone' => '6281234567801',
                'email' => 'fadly.febrian@gmail.com',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2002-02-15',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Sudirman No 1',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('fadly.febrian@gmail.com'),
            ],
            [
                'name' => 'Yulfarisa Hasnah',
                'nik' => '3275011811020002',
                'nim' => '2110512002',
                'telephone' => '6281234567802',
                'email' => 'yulfarisa.hasnah@gmail.com',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2002-03-20',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Gatot Subroto No 2',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('yulfarisa.hasnah@gmail.com'),
            ],
            [
                'name' => 'Mohammad Faishal Abyansyah',
                'nik' => '3275011811020003',
                'nim' => '2110512003',
                'telephone' => '6281234567803',
                'email' => 'faishal.abyansyah@gmail.com',
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '2002-04-10',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Thamrin No 3',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('faishal.abyansyah@gmail.com'),
            ],
            [
                'name' => 'Muhamad Kautsar Panggawa',
                'nik' => '3275011811020004',
                'nim' => '2110512004',
                'telephone' => '6281234567804',
                'email' => 'kautsar.panggawa@gmail.com',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '2002-05-12',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Rasuna Said No 4',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('kautsar.panggawa@gmail.com'),
            ],
            [
                'name' => 'Muhamad Putra Fauzan',
                'nik' => '3275011811020005',
                'nim' => '2110512005',
                'telephone' => '6281234567805',
                'email' => 'putra.fauzan@gmail.com',
                'tempat_lahir' => 'Tangerang',
                'tanggal_lahir' => '2002-06-18',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Kuningan No 5',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('putra.fauzan@gmail.com'),
            ],

            // Kelompok 2
            [
                'name' => 'Zara Zyasky Zalsabilla',
                'nik' => '3275011811020006',
                'nim' => '2110512006',
                'telephone' => '6281234567806',
                'email' => 'zara.zyasky@gmail.com',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2002-07-25',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Sisingamangaraja No 6',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('zara.zyasky@gmail.com'),
            ],
            [
                'name' => 'Adelia Deswita',
                'nik' => '3275011811020007',
                'nim' => '2110512007',
                'telephone' => '6281234567807',
                'email' => 'adelia.deswita@gmail.com',
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => '2002-08-30',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Menteng Raya No 7',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('adelia.deswita@gmail.com'),
            ],
            [
                'name' => 'Mohamad Thoriq Abdurachman',
                'nik' => '3275011811020008',
                'nim' => '2110512008',
                'telephone' => '6281234567808',
                'email' => 'thoriq.abdurachman@gmail.com',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2002-09-05',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Kemang No 8',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('thoriq.abdurachman@gmail.com'),
            ],
            [
                'name' => 'Nugraha Adhitama Haryono',
                'nik' => '3275011811020009',
                'nim' => '2110512009',
                'telephone' => '6281234567809',
                'email' => 'nugraha.adhitama@gmail.com',
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '2002-10-12',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Cikini No 9',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('nugraha.adhitama@gmail.com'),
            ],
            [
                'name' => 'Andhara Carol Saragih',
                'nik' => '3275011811020010',
                'nim' => '2110512010',
                'telephone' => '6281234567810',
                'email' => 'andhara.carol@gmail.com',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '2002-11-18',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Salemba No 10',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('andhara.carol@gmail.com'),
            ],
            [
                'name' => 'Ivan Ahmad Wijaya',
                'nik' => '3275011811020011',
                'nim' => '2110512011',
                'telephone' => '6281234567811',
                'email' => 'ivan.ahmad@gmail.com',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2002-12-22',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Tebet No 11',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('ivan.ahmad@gmail.com'),
            ],
            [
                'name' => 'Ananda Sahinaz Hidayah',
                'nik' => '3275011811020012',
                'nim' => '2110512012',
                'telephone' => '6281234567812',
                'email' => 'ananda.sahinaz@gmail.com',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2003-01-15',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Kwitang No 12',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('ananda.sahinaz@gmail.com'),
            ],
            [
                'name' => 'Damar NurFadhil Akbar',
                'nik' => '3275011811020013',
                'nim' => '2110512013',
                'telephone' => '6281234567813',
                'email' => 'damar.nurfadhil@gmail.com',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2003-02-20',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Matraman No 13',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('damar.nurfadhil@gmail.com'),
            ],
            [
                'name' => 'Olga Silvia Handayani Girsang',
                'nik' => '3275011811020014',
                'nim' => '2110512014',
                'telephone' => '6281234567814',
                'email' => 'olga.silvia@gmail.com',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '2003-03-25',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Pramuka No 14',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('olga.silvia@gmail.com'),
            ],
            [
                'name' => 'Danendra Satya Purwoko',
                'nik' => '3275011811020015',
                'nim' => '2110512015',
                'telephone' => '6281234567815',
                'email' => 'danendra.satya@gmail.com',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2003-04-08',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Pasar Minggu No 15',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('danendra.satya@gmail.com'),
            ],
            [
                'name' => "Ahmad Ro'in Fannani",
                'nik' => '3275011811020016',
                'nim' => '2110512016',
                'telephone' => '6281234567816',
                'email' => 'ahmad.roin@gmail.com',
                'tempat_lahir' => 'Semarang',
                'tanggal_lahir' => '2003-05-12',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Ragunan No 16',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('ahmad.roin@gmail.com'),
            ],
            [
                'name' => 'Alya Triananda Putri Kaluku',
                'nik' => '3275011811020017',
                'nim' => '2110512017',
                'telephone' => '6281234567817',
                'email' => 'alya.triananda@gmail.com',
                'tempat_lahir' => 'Makassar',
                'tanggal_lahir' => '2003-06-18',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Cilandak No 17',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('alya.triananda@gmail.com'),
            ],
            [
                'name' => 'Farhah Safrila Diva',
                'nik' => '3275011811020018',
                'nim' => '2110512018',
                'telephone' => '6281234567818',
                'email' => 'farhah.safrila@gmail.com',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2003-07-22',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Fatmawati No 18',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('farhah.safrila@gmail.com'),
            ],
            [
                'name' => 'Fildzah Arista Syahputri',
                'nik' => '3275011811020019',
                'nim' => '2110512019',
                'telephone' => '6281234567819',
                'email' => 'fildzah.arista@gmail.com',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '2003-08-28',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Lebak Bulus No 19',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('fildzah.arista@gmail.com'),
            ],
            [
                'name' => 'Ghania Syakira',
                'nik' => '3275011811020020',
                'nim' => '2110512020',
                'telephone' => '6281234567820',
                'email' => 'ghania.syakira@gmail.com',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2003-09-30',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Pondok Indah No 20',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('ghania.syakira@gmail.com'),
            ],
            [
                'name' => 'I Putu Widhi Satya Adnyana',
                'nik' => '3275011811020021',
                'nim' => '2110512021',
                'telephone' => '6281234567821',
                'email' => 'putu.widhi@gmail.com',
                'tempat_lahir' => 'Denpasar',
                'tanggal_lahir' => '2003-10-05',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Panglima Polim No 21',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('putu.widhi@gmail.com'),
            ],
            [
                'name' => 'Mahdiyyah Febrinazahra',
                'nik' => '3275011811020022',
                'nim' => '2110512022',
                'telephone' => '6281234567822',
                'email' => 'mahdiyyah.febriana@gmail.com',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '2003-11-10',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Senopati No 22',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('mahdiyyah.febriana@gmail.com'),
            ],
            [
                'name' => 'Moh Syaikhu Fadhli Pramudiansyah',
                'nik' => '3275011811020023',
                'nim' => '2110512023',
                'telephone' => '6281234567823',
                'email' => 'syaikhu.fadhli@gmail.com',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2003-12-15',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Dharmawangsa No 23',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('syaikhu.fadhli@gmail.com'),
            ],
            [
                'name' => 'Tegar Hartoto Rahmatulloh',
                'nik' => '3275011811020024',
                'nim' => '2110512024',
                'telephone' => '6281234567824',
                'email' => 'tegar.hartoto@gmail.com',
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => '2004-01-20',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Ampera No 24',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('tegar.hartoto@gmail.com'),
            ],
            [
                'name' => 'Yoshiki Citra Aninda',
                'nik' => '3275011811020025',
                'nim' => '2110512025',
                'telephone' => '6281234567825',
                'email' => 'yoshiki.citra@gmail.com',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2004-02-25',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Wolter Monginsidi No 25',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('yoshiki.citra@gmail.com'),
            ],
            [
                'name' => 'Ahmad Farriz Abdan Syakuran',
                'nik' => '3275011811020026',
                'nim' => '2110512026',
                'telephone' => '6281234567826',
                'email' => 'ahmad.farriz@gmail.com',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2004-03-28',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Bangka No 26',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('ahmad.farriz@gmail.com'),
            ],
            [
                'name' => 'Dina Oktaviana',
                'nik' => '3275011811020027',
                'nim' => '2110512027',
                'telephone' => '6281234567827',
                'email' => 'dina.oktaviana@gmail.com',
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '2004-04-30',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Mampang No 27',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('dina.oktaviana@gmail.com'),
            ],
            [
                'name' => 'Adinda Nazwa Nabila',
                'nik' => '3275011811020028',
                'nim' => '2110512028',
                'telephone' => '6281234567828',
                'email' => 'adinda.nazwa@gmail.com',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2004-05-05',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Kalibata No 28',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('adinda.nazwa@gmail.com'),
            ],
            [
                'name' => 'Zhafirah Aqilah Izzaturrahman',
                'nik' => '3275011811020029',
                'nim' => '2110512029',
                'telephone' => '6281234567829',
                'email' => 'zhafirah.aqilah@gmail.com',
                'tempat_lahir' => 'Tangerang',
                'tanggal_lahir' => '2004-06-10',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Duren Tiga No 29',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('zhafirah.aqilah@gmail.com'),
            ],

            // Kelompok 3
            [
                'name' => 'Samuel Halomoan Sihombing',
                'nik' => '3275011811020030',
                'nim' => '2110512030',
                'telephone' => '6281234567830',
                'email' => 'samuel.halomoan@gmail.com',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '2004-07-15',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Pancoran No 30',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('samuel.halomoan@gmail.com'),
            ],
            [
                'name' => 'Muhammad Farras Ilman',
                'nik' => '3275011811020031',
                'nim' => '2110512031',
                'telephone' => '6281234567831',
                'email' => 'farras.ilman@gmail.com',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2004-08-20',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Cawang No 31',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('farras.ilman@gmail.com'),
            ],
            [
                'name' => 'Muhammad Rifqi Fauzan',
                'nik' => '3275011811020032',
                'nim' => '2110512032',
                'telephone' => '6281234567832',
                'email' => 'rifqi.fauzan@gmail.com',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '2004-09-25',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Halim No 32',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('rifqi.fauzan@gmail.com'),
            ],
            [
                'name' => 'Lisa Febriyanti',
                'nik' => '3275011811020033',
                'nim' => '2110512033',
                'telephone' => '6281234567833',
                'email' => 'lisa.febriyanti@gmail.com',
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => '2004-10-30',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Condet No 33',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('lisa.febriyanti@gmail.com'),
            ],
            [
                'name' => 'Abdu Hafizh Nurfalah',
                'nik' => '3275011811020034',
                'nim' => '2110512034',
                'telephone' => '6281234567834',
                'email' => 'abdu.hafizh@gmail.com',
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '2004-11-05',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Kramat Jati No 34',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('abdu.hafizh@gmail.com'),
            ],
            [
                'name' => 'Farrel Al Faqih Ekatama',
                'nik' => '3275011811020035',
                'nim' => '2110512035',
                'telephone' => '6281234567835',
                'email' => 'farrel.alfaqih@gmail.com',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2004-12-10',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Jatinegara No 35',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('farrel.alfaqih@gmail.com'),
            ],
            [
                'name' => 'Rizal Alief Fairuzzaki',
                'nik' => '3275011811020036',
                'nim' => '2110512036',
                'telephone' => '6281234567836',
                'email' => 'rizal.alief@gmail.com',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '2005-01-15',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Duren Sawit No 36',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('rizal.alief@gmail.com'),
            ],
            [
                'name' => 'Sendi Wildanto',
                'nik' => '3275011811020037',
                'nim' => '2110512037',
                'telephone' => '6281234567837',
                'email' => 'sendi.wildanto@gmail.com',
                'tempat_lahir' => 'Surabaya',
                'tanggal_lahir' => '2005-02-20',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Cipayung No 37',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('sendi.wildanto@gmail.com'),
            ],
            [
                'name' => 'Sazkia Alifiah Suciana',
                'nik' => '3275011811020038',
                'nim' => '2110512038',
                'telephone' => '6281234567838',
                'email' => 'sazkia.alifiah@gmail.com',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2005-03-25',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Pondok Gede No 38',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('sazkia.alifiah@gmail.com'),
            ],
            [
                'name' => 'Patricia Nessa Mae',
                'nik' => '3275011811020039',
                'nim' => '2110512039',
                'telephone' => '6281234567839',
                'email' => 'patricia.nessa@gmail.com',
                'tempat_lahir' => 'Medan',
                'tanggal_lahir' => '2005-04-30',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Bekasi Timur No 39',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('patricia.nessa@gmail.com'),
            ],
            [
                'name' => 'Difa Ananda Nursalsabil',
                'nik' => '3275011811020040',
                'nim' => '2110512040',
                'telephone' => '6281234567840',
                'email' => 'difa.ananda@gmail.com',
                'tempat_lahir' => 'Tangerang',
                'tanggal_lahir' => '2005-05-05',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Cakung No 40',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('difa.ananda@gmail.com'),
            ],
            [
                'name' => 'Fathir Deny Syahputra',
                'nik' => '3275011811020041',
                'nim' => '2110512041',
                'telephone' => '6281234567841',
                'email' => 'fathir.deny@gmail.com',
                'tempat_lahir' => 'Palembang',
                'tanggal_lahir' => '2005-06-10',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Pulomas No 41',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('fathir.deny@gmail.com'),
            ],
            [
                'name' => 'Aura Rachmawaty',
                'nik' => '3275011811020042',
                'nim' => '2110512042',
                'telephone' => '6281234567842',
                'email' => 'aura.rachmawaty@gmail.com',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '2005-07-15',
                'jenis_kelamin' => 'P',
                'alamat' => 'Jl. Rawamangun No 42',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('aura.rachmawaty@gmail.com'),
            ],
            [
                'name' => 'Ikhsan Fathirizky Ramadhanu',
                'nik' => '3275011811020043',
                'nim' => '2110512043',
                'telephone' => '6281234567843',
                'email' => 'ikhsan.fathirizky@gmail.com',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '2005-08-20',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Kelapa Gading No 43',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('ikhsan.fathirizky@gmail.com'),
            ],
            [
                'name' => 'Farhan Abu Bakar',
                'nik' => '3275011811020044',
                'nim' => '2110512044',
                'telephone' => '6281234567844',
                'email' => 'farhan.abubakar@gmail.com',
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => '2005-09-25',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Pluit No 44',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('farhan.abubakar@gmail.com'),
            ],
            [
                'name' => 'Muhammad Rafli Alfiardi',
                'nik' => '3275011811020045',
                'nim' => '2110512045',
                'telephone' => '6281234567845',
                'email' => 'rafli.alfiardi@gmail.com',
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '2005-10-30',
                'jenis_kelamin' => 'L',
                'alamat' => 'Jl. Sunter No 45',
                'kebangsaan' => 'Indonesia',
                'pekerjaan' => 'Mahasiswa',
                'pendidikan' => 'S1 Sistem Informasi',
                'jurusan' => 'S1 Sistem Informasi',
                'photo_diri' => null,
                'photo_ktp' => null,
                'photo_sertifikat' => null,
                'photo_ktmkhs' => null,
                'photo_administatif' => null,
                'tanda_tangan' => null,
                'user_type' => 'asesi',
                'password' => Hash::make('rafli.alfiardi@gmail.com'),
            ],
        ];

        foreach ($asesiData as $data) {
            User::create($data);
        }
    }
}
